"""add finding model column

Revision ID: 5948bcd703ff
Revises: c4d7a33c9945
Create Date: 2026-07-30 07:49:22.539223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5948bcd703ff'
down_revision: Union[str, Sequence[str], None] = 'c4d7a33c9945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'model')
    # ### end Alembic commands ###
