"""add target_version error_message column

Revision ID: 96a070c6af64
Revises: 5948bcd703ff
Create Date: 2026-07-30 12:50:47.859787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96a070c6af64'
down_revision: Union[str, Sequence[str], None] = '5948bcd703ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_versions', sa.Column('error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('target_versions', 'error_message')
    # ### end Alembic commands ###
