"""initial schema

Revision ID: c4d7a33c9945
Revises: 
Create Date: 2026-07-28 09:19:42.136840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4d7a33c9945'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('confirmed_gender', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title_id', sa.String(), nullable=False),
    sa.Column('episode_no', sa.Integer(), nullable=True),
    sa.Column('video_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title_id', sa.String(), nullable=False),
    sa.Column('speaker_character_id', sa.String(), nullable=False),
    sa.Column('addressee_character_id', sa.String(), nullable=False),
    sa.Column('confirmed_formality_level', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['addressee_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['speaker_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('episode_id', sa.String(), nullable=False),
    sa.Column('target_language', sa.String(), nullable=False),
    sa.Column('variant', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('target_version_id', sa.String(), nullable=False),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finding_count', sa.Integer(), nullable=False),
    sa.Column('reflection_rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['target_version_id'], ['target_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learned_examples',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('target_version_id', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('example', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['target_version_id'], ['target_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('target_version_id', sa.String(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.Column('korean_text', sa.String(), nullable=False),
    sa.Column('target_text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['target_version_id'], ['target_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('target_version_id', sa.String(), nullable=False),
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('original_text', sa.String(), nullable=False),
    sa.Column('suggested_text', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('final_text', sa.String(), nullable=False),
    sa.Column('reviewer_name', sa.String(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.ForeignKeyConstraint(['target_version_id'], ['target_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stt_corrections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.Column('original_text', sa.String(), nullable=False),
    sa.Column('corrected_text', sa.String(), nullable=False),
    sa.Column('reviewer_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stt_corrections')
    op.drop_table('findings')
    op.drop_table('segments')
    op.drop_table('learned_examples')
    op.drop_table('exports')
    op.drop_table('target_versions')
    op.drop_table('relationships')
    op.drop_table('episodes')
    op.drop_table('characters')
    op.drop_table('titles')
    # ### end Alembic commands ###
